import { Hono } from 'hono';
import auth from './auth.js';
import dashboard from './dashboard.js';
import statistics from './statistics.js';
import students from './students.js';
import payments from './payments.js';
import reminders from './reminders.js';
import offlinePayments from './offline-payments.js';
import refunds from './refunds.js';
import finance from './finance.js';
import invoices from './invoices.js';
import documents from './documents.js';
import materials from './materials.js';
import scholarships from './scholarships.js';
import loans from './loans.js';
import dormitories from './dormitories.js';
import checkin from './checkin.js';
import uniform from './uniform.js';
import supplies from './supplies.js';
import messages from './messages.js';
import files from './files.js';
import exportRoutes from './export.js';
import events from './events.js';
import reports from './reports.js';

const staff = new Hono();

staff.route('/', auth);
staff.route('/', dashboard);
staff.route('/', statistics);
staff.route('/', students);
staff.route('/', payments);
staff.route('/', reminders);
staff.route('/', offlinePayments);
staff.route('/', refunds);
staff.route('/', finance);
staff.route('/', invoices);
staff.route('/', documents);
staff.route('/', materials);
staff.route('/', scholarships);
staff.route('/', loans);
staff.route('/', dormitories);
staff.route('/', checkin);
staff.route('/', uniform);
staff.route('/', supplies);
staff.route('/', messages);
staff.route('/', files);
staff.route('/', exportRoutes);
staff.route('/', events);
staff.route('/', reports);

export default staff;
